name: Build and push Docker images

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          cd cart-service
          ./gradlew build
          docker build -t ahmedgodaa/cart-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/cart-service:${{ github.event.inputs.version }}
          cd ../customer-service 
          ./gradlew build  
          docker build -t ahmedgodaa/customer-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/customer-service:${{ github.event.inputs.version }}
          cd ../file-service
          ./gradlew build     
          docker build -t ahmedgodaa/file-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/file-service:${{ github.event.inputs.version }}
          cd ../product-service
          ./gradlew build          
          docker build -t ahmedgodaa/product-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/product-service:${{ github.event.inputs.version }}
          cd ../user-service 
          ./gradlew build
          docker build -t ahmedgodaa/user-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/user-service:${{ github.event.inputs.version }}
