name: Build and push Docker images

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Image Version
        default: v1.0.0
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and Push Cart Service Docker image
        run: |
          cd cart-service
          chmod +x gradlew
          ./gradlew build
          docker build -t ahmedgodaa/cart-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/cart-service:${{ github.event.inputs.version }}
          
      - name: Build and Push Customer Service Docker image
        run: |
          cd customer-service
          chmod +x gradlew
          ./gradlew build
          docker build -t ahmedgodaa/customer-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/customer-service:${{ github.event.inputs.version }}

      - name: Build and Push File Service Docker image
        run: |
          cd file-service
          chmod +x gradlew
          ./gradlew build 
          docker build -t ahmedgodaa/file-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/file-service:${{ github.event.inputs.version }}
          
      - name: Build and Push Product Service Docker image
        run: |
          cd product-service
          chmod +x gradlew
          ./gradlew build
          docker build -t ahmedgodaa/product-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/product-service:${{ github.event.inputs.version }}
          
      - name: Build and Push User Service Docker image
        run: |
          cd user-service
          chmod +x gradlew
          ./gradlew build
          docker build -t ahmedgodaa/user-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/user-service:${{ github.event.inputs.version }}


